language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
<<<<<<< HEAD
script: nosetests --with-coverage
=======
script: nosetests --with-coverage
>>>>>>> develop
